version: '3.6'
services:
  mysql:
    image: mysql:5.7
    networks:
      - app_network
    env_file:
      - ./.env
    ports:
      - 3306:3306
    restart: unless-stopped
networks:
  app_network:
    driver: bridge